### ISSUE TITLE
Change structure of how flavorDetails is defined in JSON schema

### ISSUE THREAD

**Issue by rdb** [bible-technology/scripture-burrito#110]
See meeting minutes of Dec 5th for what was agreed upon for the flavor syntax.

**Comment by mvahowe** [comment]
I'm not totally against a MIME-type representation, but I don't think it's going to make processing easier since, in many places in my processing model, we need to deal with the flavorType on its own. That's one way that this is different to a MIME type, where the "text" of "text/xml" is rarely useful in isolation.

**Comment by jag3773** [comment]
FlavorType
  * Name: scripture
  * Details: { The parts controlled by such (canonSpec) }
  * Flavor
      * Name: text
      * Details: { The parts controlled by such (flavordetails) }

**Comment by mvahowe** [comment]
I looked at the flavor names, in the light of concerns that unscrupulous devs might try to parse them for meaning. The problem is that, once you try to address this, you quickly realise that people naturally pick names with semantics, and that avoiding this entirely ends up feeling very contrived. In other words, unless we change scriptureText to "bob" and scriptureAudio to "marieClaude", or maybe use UUIDs, someone somewhere is going to try to parse the names, and I think that's just a _caveat emptor_ thing.

That said, here's a set of suggestions that might address some of the recurring confusion in our own conversations, especially the "it's not a mimetype" one. I've gone for ClassCase since a flavor seems to me to be a class sort of thing. I've added some vaporware flavors in an attempt to answer the recurring "what goes in the box" question.

*scripture:*

* TextTranslation (scriptureText)

* AudioTranslation (scriptureAudio)

* SignLanguageTranslation (scriptureVideo)

* TypesetScripturePublication (scripturePrint)

* BrailleScripturePublication (scriptureBraille)

* _FilmScripturePublication_ (eg Jesus film)

*gloss:*

* TextStories (eg uW Bible stories)

* _SignLanguageStories_ (aka CBT "translations")

* _TypesetBibleStories_  (eg uW Bible stories in a PoD format)

*parascriptural:*

* WordAlignment (wordAlignment)

* _TextCommentary_ (eg Matthew Henry Commentary)

* _TextTranslationNotes_ ("stuff that might help you to translate this verse")

* _GenericVideoTemplate_ (eg Lumo generics)

*peripheral:*

* Versification (might need more than one of these depending on use cases)

* _Maps_

* _NameIndex_ (Curated list of verses for major characters, disambiguating namesakes)

**Comment by jag3773** [comment]
That looks sensible to me @mvahowe, seems to address the reduplication issue and also provide a bit more information about the flavor itself.

**Comment by rdb** [comment]
I'm fine with that (except I don't get the argument to make it ClassCase at all)

**Comment by mvahowe** [comment]
This is now in the 0.2 develop branch.
