### ISSUE TITLE
Variants are the New Publication

### ISSUE THREAD

**Issue by mvahowe** [bible-technology/scripture-burrito#122]
# The story so far

In the current proposal, for each entry/revision, SB has

- one metadata document
- zero or more publications, described in this single document
- a notion of "variant" inspired by the need, within DBL, to modify the content of individual USX files to comply with licenses, and to allow the state of a translation between two revisions to be represented as a burrito.

We can thus end up with a revision that has multiple variants, each of which may have multiple publications. This is complex to work with, and it doesn't seem to handle all publishing scenarios either. One big limitation is that all publications share the same metadata. (There is a mechanism for overriding some fields at the publication level, but this has proved confusing, and it doesn't allow for, eg, different publications with different book names or copyright notices.)

# Variants make multiple publications redundant
## The big idea
- Each entry/revision contains one or more variant
- The default variant corresponds to the master copy of the project. It does not contain a publication. It does contain recipes and resources for producing derived variants.
- Derived variants draw on some or all of the Scripture text in the default variant. ie all variants in an entry/revision that contain John 3 contain the same content for John 3.
- Derived variants are considered to be "fixed". They may be used for publication or reference, but should never be modified directly. Instead, the default variant and its recipes are updated and used to produce a derived variant for the next revision of the entry.
- Derived variants contain exactly one publication, which describes the ordered content to be published. The publication goes beyond ordering PT books to allow hierarchies, editorial material, parts of books and peripherals, etc.

## So what?
- Instead of one metadata.json file, we have metadata-default.json, metadata-derived-birthnarratives.json, etc.
- Instead of licensing publications, DBL would license entry/revision/variants
- Instead of rewriting USX as it is served, DBL would generate variants once as a post-upload hook
- There is no need to allow names etc to be overridden in the publication section. Instead, each derived variant has the metadata it needs, once. This makes processing easier and less ambiguous.
- It becomes possible to customise almost any metadata for each variant (book names, copyright, promotional information...)
- It becomes possible to license some or all of "source"content along with some or all of "release" content, rather than the binary "owner or not" approach of DBL.
- It becomes possible to manage quite large numbers of derived variants in a modular way. No metadata document contains more than one publication, and the process for producing each publication is defined explicitly.
- It becomes possible to imagine derived variants which look radically different to a BCV Bible, but which use the same Scripture content. eg, in the context of incremental publishing, it would be possible to produce a lectionary or the birth narratives.
- It is still possible to ship multiple publications in a single "package" simply by including multiple variant metadata document plus the union of resources needed by all those metadata documents.

# Awoooga, Not Everything Is a Variant
The variant model assumes that
- subsets of the same Scripture translation are being used
- the document consists primarily of Scripture
- the document can be generated using a recipe
- the resources belong on the same flavor as the default variant

thus

- a PDF from Publishing Assistant would not be a variant of a textTranslation because textTranslations do not use the PDF format, and because there is a human element in producing PA output.
- an audio recording of a textTranslation would not be a variant of a textTranslation because textTranslations do not use the audio format, and because (barring robotic madness) there is a human element to producing audio output.
- a book of devotions with a short Bible quote at the top of each chapter would not be a variant because the content is not primarily Scripture.
- a concordance based on the textTranslation would not be a variant because textTranslations do not include concordances.
- a braille transcription of a textTranslation would not be a variant because textTranslations do not use the PEF format.

# What Implementation Looks Like
In increasing order of complexity and decreasing order of urgency:
1. Incorporate this model into the evolving JSON schema, before we get to #107 
2. Create a recipe spec that enables us to do at least what DBL publications allow now
3. Develop more complex recipe functionality to handle more ambitious incremental publishing needs
4. Implement derived variant generation using recipes.

**Comment by rdb** [comment]
I can see how this would work, but I need to form a better picture of how the Registry would deal with this, especially in light of the ongoing incremental publication discussions.

In this proposal, where does metadata that describes the translation project (as opposed to the specific publication) live?  The Registry metadata for a project describes the translation project; the scope may be "whole bible" even if there are only a (complete) Mark and Luke as yet, and the name will be something like "Dutch Bible and Literacy Project".  Would this go into the "default" metadata, with the publications as variants?

**Comment by mvahowe** [comment]
I think that, for the Registry, it's pretty simple, assuming the Registry is about translation rather than publication. The default variant has all the translated content plus the metadata that describes the project in general, but not the publication(s), which I believe is the way things currently work. Depending how we do the recipes, the Registry could include them too.

**Comment by rdb** [comment]
As you know, I'm pushing for the Registry to store publication metadata as well.  Would the Registry then need to store a variant tree of metadata objects?

What kind of information does a recipe include?  Does it include any metadata?

**Comment by mvahowe** [comment]
In my current, provisional thinking, the default entry contains everything needed to make any of the publications. I'm imagining that a recipe will be a DSL. (The current publication element can be seen as a DSL, albeit a rather impoverished one.) I imagine the DSL going through multiple iterations as we find all the DBL edge cases, as PT firms up its incremental publishing intentions, and as other stakeholders add their needs. Off the top of my head I'd imagine, at least,

- a way to override fields in the default metadata
- an ordered, hierarchical description of the publication content
- any non-scriptural content that needs to be "merged" into that publication
- a way to specify pruning of USX in some well-known ways

It feels to me like the recipes might be a flavor, in which case the default variant would actually link to the appropriate recipes rather than including them. This would mean that the recipes can be reused (ie we don't need to reinvent "Lutheran Canon" 1000 times.)

How well this works for the Registry really depends what the Registry wants to do with publications. The recipe form isn't going to be as easy to introspect for certain types of information. But, if the Registry is not primarily about publishing, that may not be a problem.

I do expect the recipes to be explicit and technology-agnostic, so, if necessary, the Registry could "cook" the recipes to make a publication at any point.

A more interesting question is surely what GBC does with all this.

**Comment by rdb** [comment]
One of the things UBS is thinking about is having a system for planning publication goals ahead of time (possibly ahead of the existence of the PT project), and ideally I think that means that PT would pull metadata for the publication goals from the Registry.  I would hope that remains possible in recipe form.

As for GBC, it will want to be concerned solely with the generated variant metadata, since GBC needs to contain a record of the publication (and get out of this awkward position where it stores a snapshot of the translation metadata, which just doesn't make sense for incrementally published projects).  This does require variants to have a unique and stable identifier (but DBL wants this too, so I assume you're planning on providing one).

**Comment by mvahowe** [comment]
My understanding of "a publishing goal" is a lot like my plans for a recipe. It's not (initially) the finished work, but it does describe what that work will look like.

In DBL right now, the unique identifier of a snapshot of a publication is

```
entry/revision/publication
```
In SB (in this proposal) it becomes
```
idServer/entry/revision/variant
```
This does raise an interesting question about the immutability of recipes. To jump to my (provisional) conclusion, I think this is an argument for making recipes first-class flavors and linking to a specific revision of a recipe, to ensure that it is always possible to reconstruct previous revision variants as the recipe evolves.

No, I don't think we want to support variants of recipes :-)

**Comment by mvahowe** [comment]
@rdb and I had a conversation about what recipes should allow. The following would, I think, allow everything that DBL and PT currently do, in a declarative format:
```
metadata:
   identification/name: The Birth of Jesus (Good News Translation)
   copyright/something: (c) American Bible Society 2020
scripture:
  removeFootnotes: yes
  removeXRefs: no
  removeVerses: no
  removeWJMarkup: yes
  oneVersePerPara: yes
content:
  contents: depth=1
  section: Understanding the Birth Narratives
    editorial: birth_narratives_frontmatter
  section: The birth of Jesus in Luke's Gospel
    editorial: lukan_birth_narratives_intro
    scripture: LUK 1-2
  section: The birth of Jesus in Matthew's Gospel
    editorial: matthian_birth_narrative_into
    scripture: MAT 1-3
  section (appendix): The Messiah's Birth in the Old Testament
    editorial: intepreting_old_testament_prophecies
    scripture: DEU.18.15
    scripture: EZK 37.24,26-27
```
(The format for describing recipes needs to be decided. I favour some sort of DSL that is human readable, and which an archivist might be able to edit. If the aim is for no-one to be able to edit these manually, we should go with JSON and represent Scripture references as nested objects.)

**Comment by klassenjm** [comment]
@mvahowe Mark - This proposal for variants, and on how they could act as a replacement for publications, looks really good to me. This really seems like a much more maintainable and substantial improvement over the current multiple-publications-single-metadata. Recipes sound close / idential to what would be designated as a publication definition in the incremental publication specification work.

Default variant, and derived variants drawing on default variant content.

The ability to distribute exactly and only what is intended for a particular publication - while keeping that publication in sync with default content. I think this would provide a necessary level of confidence that what will be published (especially incrementally) is what is intended.

I would look forward to what others think.

**Comment by mvahowe** [comment]
There's a lot of detail to unpick, but I think one benefit of this is that we have a translation-type variant ("default") plus one or more publication-type variant (derived_*). This gives us an opportunity to end up with two cleaner shapes of metadata, rather than our current route of taking everything DBL did and trying to add everything that PTReg does into one schema where almost everything is optional.

So, eg,

- default never has a license. (If you want to license the entire project, you make a derived variant that contains everything, plus a license, and I think there should be a standard recipé to do that.)
- The whole "source" thing goes away. Everything in "default" is considered to be a source, and publications only contain what has been "released" (in DBL terms). This makes for shorter documents, allows for licensing of selective project sources, and also makes accidental release of the sources less likely.
- default doesn't need the promotion section, and may not need the copyright section either. (ISTM that an unpublished, unlicensed project has no copyright and, even if it does, publications might well need modified versions of that copyright, so publication copyright should be part of the recipe, not a copy-and-paste of the project copyright.)

**Comment by mvahowe** [comment]
(This does reopen the USFM/USX debate though. If we apply variant logic to the last of our definitive decision on this, "default" would contain USFM, derived variants would contain USX, and USFM to USX conversion would be part of the recipe.)

**Comment by jag3773** [comment]
I'm generally in favor of the direction given here.  However, everything needs to have a license and copyright owner defined, including `default`.  Because copyright happens automatically from a legal perspective we can't pretend that something *doesn't have one*.  Now that doesn't mean that we necessarily need a full statement or copyright page text in a `default` entry, but we must represent reality in the `default` variant by identifying who owns it and what the license is ("All rights reserved" is the legal default).

In some cases the license of the `default` entry could restrict the type of derived licenses that may be applied.  I'm not suggesting that we have to model these relationships in the schema but we do need to present them.

**Comment by mvahowe** [comment]
I can see why we need a copyright owner. I'm not sure what a license looks like for a project I'm not going to tell anyone else about. It's surely a "If a tree falls in a forest and no-one hears it does it make a sound" sort of thing. I don't think it's possible to write a license intended for zero people. (If it is then, logically, it could say anything, like "if false then ...".)

**Comment by jag3773** [comment]
Possible distinction: A flavor cannot be derived, but a variant must be derived via a recipe.

**Comment by jonathanrobie** [comment]
I am generally in favor of this direction.

I need time to work through a variety of scenarios across systems with
people on the editing side, people on the publishing side, and the systems
on both sides and in between.

I do think copyright and licensing matters from the very beginning.  When I
work with people, we sometimes have a different license for the project at
the beginning (e.g., "don't share this until we agree that it's good enough
that it isn't too terribly embarrassing, but if none of us gets this done
by a certain date, the others are free to pick it up and run with it") than
we will at the end (for me, this is usually some Creative Commons license,
many publishers will have something different).   If a publisher never
intends to freely license their work, this is less of a problem, but I
think the reputation of freely licensed materials can sometimes suffer
because early versions are clearly unfinished and not up to the level of
quality expected in the final product.

I don't know how many people do things that way, but I would like it to be
possible.

**Comment by mvahowe** [comment]
I think this is one place where it's hard to define SB independently of assumptions about the processing model.

In my current thinking on variants, at least in terms of how they would work in DBL, the default variant is never released to anyone other than the owner, period. If you want others to see your work in progress in all its messy splendour, an ecosystem like PT lets you add users to your team. If you do want to give others your work in progress in all its messy splendour, with a license, you spin off a variant that contains everything and that has a license appropriate to the people you want to share it with. (I think that the "identity recipe" should be the first one we define, which does exactly that, and which should always be available.)

**Comment by mvahowe** [comment]
My epiphany for the day came from thinking about @rdb 's observation that an abstract recipe does not contain metadata but the instantiated recipe for a specific default variant does. So the variant producer is effectively taking the no-metadata function as an argument and adding the metadata as a new argument.

I believe that the technically correct way to describe this would be currying the recipe :-)

**Comment by jonathanrobie** [comment]
A Paratext team can share a project with another individual or another team
using the Paratext registries, regardless of status.  This can help other
teams with their translation work even before a given translation is really
ready for publishing.

With incremental publishing, I suspect that we will also need to have
publications in the Paratext registries in addition to projects. At this
point, these publications have not been realized as PDF, print, or
whatever.  These publications would then be added to the DBL.  To make that
possible, they have to contain the information that DBL needs, including
copyright and licensing for each publication.

This is the chain that I want to think through in order to be clear about
our requirements. I want to make sure it works for various approaches to
publishing at various stages.

Jonathan

**Comment by jag3773** [comment]
I agree @jonathanrobie , I guarantee that our `default` will be seen and edited by multiple people and I think that holds for 99% of translation projects.

But, irrespective of workflow or distribution, as I said above *every creative work has an owner and a license by default,* we need to encode that reality from the start @mvahowe .

**Comment by mvahowe** [comment]
@jonathanrobie @jag3773 If, as I think you've both suggested, your respective ecosystems plan to treat SB as an import/export format, rather than as an internal format, in what case would we have, eg, a PT-originated burrito that isn't being deliberately shared? As I understand the current plan,

> A Paratext team can share a project with another individual or another team using the Paratext registries, regardless of status

does not involve any burritos, so we're talking about how to put copyright into a burrito that doesn't exist.

**Comment by jonathanrobie** [comment]
@mvahowe <https://github.com/mvahowe> When I work on a project, we clarify
copyright and licensing from the very beginning, every member of the team
needs to know what will happen with their work.  I want to be able to refer
to it if there is any question. So even in a project, I want this.

Beyond that, the Paratext Registry is also a medium of sharing, and some
resources are shared via the registry even if they are not in DBL.  This
includes resources that DBL does not include by design, also resources that
are only being shared with other translation teams, specific consultants,
etc.  With incremental publishing, a project no longer corresponds 1:1 to a
resource.  So we might have a variety of incremental publications that each
have their own status and license.  They might also have different
copyright holders, though this is much less likely.  So to be more precise,
when I said this:

> A Paratext team can share a project with another individual or another
team using the Paratext registries, regardless of status

That might involve a Paratext project or an incremental publication.  I
would really like to be able to let incremental publications be Scripture
Burritos.

Beyond that, I have spent too much of my life trying to find someone who
can claim to own a resource who can definitively tell me what people are
allowed to do with it.  There are resources that could probably be freely
distributed if we knew what the resource creator intended.   There are
resources that were worked on by more than one team where clarifying who
owns what is difficult.

**Comment by mvahowe** [comment]
@jonathanrobie If it's a Paratext project, it's not a SB issue. If it's a SB publication, it has a license.

I agree that everything should have copyright assigned. I don't see how everything can have a licence, it simply makes no sense. The Oxford Concise Dictionary defines "licence" as "formal or official permission". If you don't give permission, it isn't a licence. The verb "license" means "to authorize something". If you don't authorize anything, you're not licensing it.

If you still disagree, please show me what a license to not give away any rights looks like. The two options I see are
```
I the owner grant a licence to nobody at all to do <doesn't matter>"
```
or
```
I the owner grant a license to <doesn't matter> to do nothing.
```
Can you do any better? How do you license nothing or, alternatively, give nobody a licence?

**Comment by rdb** [comment]
The plan that I have been counting on so far that the Registry, whose main job it is to store metadata (not content), will be able to store or provide the metadata following the Scripture Burrito metadata spec.  It will want to consider the question of copyright for the content even in absence of any content.  So unless we want to ignore the usage model of storing and processing metadata that isn't (yet) part of a burrito, the question of describing copyright as part of the metadata does exist.  And copyright ownership information is (as far as I've seen) part of the translation brief of a project, so this information does precede the existence of any content.

I don't know how much licensing information would be part of that.  Right now, the Registry doesn't really have a licensing model, because the Registry doesn't really publish content.  But I could certainly imagine a project deciding on, say, a public license, before they start producing content, and wanting to have this recorded in the metadata.

**Comment by jonathanrobie** [comment]
@mvahowe I can allow you to read something, use it in translation work,
discuss with other people, use it for community checking, create alpha
versions in various formats for very limited circulation.  The license can
specify who is allowed to use it and how before it is actually released.

It's not all-or-nothing.

**Comment by klassenjm** [comment]
Hi ... not been able to keep up with this conversation, but I have noticed something in the terms being used.  @jonathanrobie Sometimes you have referred to the Registry or the Paratext registries (plural). For example:

> Beyond that, the Paratext Registry is also a medium of sharing, and some
resources are shared via the registry even if they are not in DBL.  This
includes resources that DBL does not include by design, also resources that
are only being shared with other translation teams, specific consultants,
etc. 

Could we clarify whether you are always referring to the Registry (registry.paratext.org)? I'm wondering if you're also referring to Send/Receive servers (as another 'registry'), and in this sense you were saying that the Registry is a means of sharing other resources. If we all mean Registry =registry.paratext.org, then the Registry does not hold any resources (content). Correct?

Perhaps when discussing we can say Registry (registry.paratext.org), and S/R (Send/Receive system) separately, to be clear.

**Comment by mvahowe** [comment]
@mvahowe It's not all or nothing, but sometimes it's definitely nothing, and you're saying that there's always a licence, so I need to know what a "nothing" licence looks like.

**Comment by mvahowe** [comment]
> I can allow you to read something, use it in translation work, discuss with other people, use it for community checking, create alpha versions in various formats for very limited circulation.  The license can specify who is allowed to use it and how before it is actually released.

That's the perfect example of when we'd make an identity variant with a licence. And you'd do the same for the next 10 slightly different cases in which you want to share the project, which gives you much finer grained control than one catch-all licence in the project.

**Comment by rdb** [comment]
@klassenjm The Registry is what nowadays controls access to the S/R server, so while it's the S/R server storing the content, it's the Registry that determines who gets to see what.

Unless I misunderstand, Jonathan is foreseeing the possibility that Registry might be used for licensing projects on the S/R server for use by wider audiences than just the team itself in the future.

**Comment by mvahowe** [comment]
@rdb Can the Registry give access to only selected files on S/R? If not it seems like licenses are going to be quite basic. ie it won't be possible to only license the NT of a project.

In any case, if the Registry ends up doing licensing, and PT is not using SB internally, I can't see how this is a SB issue.

**Comment by rdb** [comment]
I can see how the Registry licensing internal PT stuff isn't an SB issue, but the Registry does use SB for metadata storage, and does need to record copyright info in general, as well as public licenses (eg. CC), because PT relies on the Registry to produce the metadata when exporting bundles.

**Comment by mvahowe** [comment]
I think we're all agreed on the need to store copyright.

I'm expecting license information for an exported, derived variant to be in an instantiated recipe.

**Comment by jonathanrobie** [comment]
Back to my earlier email.

I think we need to have conversations among different subsets of our
ecosystem to discuss how this should work, now and in the near future when
we add things like incremental publishing and resource authoring.  I would
like to start with users at both ends of the system and then discuss it
with architects responsible for the bits in the middle.  I think that will
take a few weeks to do right.

I think the conversation in this issue illustrates the need for that.

**Comment by jonathanrobie** [comment]
@mvahowe <https://github.com/mvahowe> You seem to have a strong objection
to allowing licenses to be stored.

Why?

**Comment by mvahowe** [comment]
@jonathanrobie I have a strong objection to storing a licence that isn't a licence. A licence that licenses nothing, or to no-one, is not a licence. My proposal above explains how to store licences that are licences.

**Comment by jonathanrobie** [comment]
@mvahowe Are you trying to limit what people can say in a license? Or when
they might choose to use one?  I don't think a single example I have given
"licenses nothing, or to no-one".   I don't think the system should
restrict users from doing what they need to do.

Why not leave this up to the users?

**Comment by klassenjm** [comment]
Me again -- 
I wonder (again) if there is something causing misunderstanding.

Earlier in this thread, Jonathan said:

> When I work on a project, we clarify copyright and licensing from the very beginning

I *think* Mark was just trying to say that he did not know how licensing could be identified for a project at the beginning, when nothing in it yet has been identified as product to use (to publish or adapt etc) or what can be done with it --- at least not in the sense of how licensing has been done via DBL for the most part. For the most part, it (a license) is for authorizing a use of something for a specific purpose (the definition earlier). We could also call that an 'license agreement".

The case which is a little different in practice would be when someone attaches a public license (e.g. CC) to their project content right from the start. That scenario is one when I can see having copyright and licensing decided from the start. But even then, there is actually a license agreement, but the text of it is usually just linked / pointed to. If a project is not planning to use a public license, then I believe Mark is just saying that there cannot be an empty license. @mvahowe ? I don't think the implication is trying to limit what can be in a license.

**Comment by mvahowe** [comment]
@klassenjm Yes, that's what I'm saying. You can't licence nothing to nobody. That's limiting in the same way as an engineer refusing to manufacture 4-dimensional parts. It simply doesn't make sense.

As you say, someone could say up front that the project is going to be CC, which I think implies that the day to day work on the project is in some sense public. Since SB is  about snapshots, that seems out of scope to me, but I don't think that prevents someone from working in public. If, where and when people use licenses outside of SB is not an SB issue.

Typically, if you wanted to share work in progress under a licence, you'd give access to the repo and drop in a LICENSE file. AFAICS, PT could do that tomorrow. Or PT could do something else.

An idServer implementation might decide to hang one licence off a project from day one, as a way to generate publications later. Personally, I think that's a bad implementation because
* the "licence" of the work in progress may well not be the same as the licence required for publishing
* this can only encourage a "click-through" approach where the wrong licence ends up on the published work. I'd prefer publishing to be a deliberate act rather than relying on something someone typed in 10 years previously (in order to get the form submitted).
* it is quite common for the same project to be licenced differently to different organizations for different purposes at various times. In that common scenario, what does "the project licence" mean?

But it's not my job or my aim to police how other people build their systems and, even if it were, this wouldn't be the place to do it.

I think that our job here is to come up with a data model and associated processing model that represents snapshots of Bible-related data in a convenient and predictable format, and which allows for robust, transparent and scalable processing of that data. That's what I'm proposing here. Attaching zero or more publishing recipes to the default variant is more powerful and flexible in every way than requiring exactly one licence from day one. I don't think that this proposal rules out anything that I've heard anyone say they want to do, it just attempts to represent all those possibilities in a consistent and comprehensible way.

And I do want to say, again, that end user requirements engage with this type of discussion in a rather indirect way. I doubt that the design of SSL was driven by end user stories. *"As a bank customer I want my data to be safe so that criminals don't steal all my money"* would not have helped them to hone their technical spec, in my opinion, and requirements based on how most users think digital security works would have been an absolute disaster.

**Comment by jag3773** [comment]
@mvahowe I do think that I've answered your question above. Absent anything else, the legal default license is "All Rights Reserved."  So I would expect the SB `default` entry to say:

>Owner: "Someone/Some Org"
>License: "All Rights Reserved"

unless they picked something else, like a public CC license.

**Comment by mvahowe** [comment]
@jag3773 I'd expect the copyright statement to say
```(c) Owner, All Rights Reserved```

Although the Interweb is not especially flattering about this, eg

https://en.wikipedia.org/wiki/All_rights_reserved

*"it is unclear if it has any legal effect in any jurisdiction"*

In other words, it's a bit like those copyright statements that get copied and pasted by gullible Facebook users :-)

Regardless, "All rights reserved" is not a licence. You can't licence "all rights reserved" to anyone. It's an oxymoron.

**Comment by mvahowe** [comment]
Once the latest set of PRs are merged, I'm going to rework the schema structure so that the top-level schema is just a skeleton that references other documents. Then we can put a document above that that looks for one of a number of different skeletons, depending on the variant.

**Comment by jag3773** [comment]
> Regardless, "All rights reserved" is not a licence. You can't licence "all rights reserved" to anyone. It's an oxymoron.

Yes, but despite the semantics, it's the status quo.  `License: None` would also work from my perspective.

**Comment by jag3773** [comment]
@mvahowe Relative to file naming, what is the use case for having separate file names per variant? It seems easier to be to have 1 well known location for SB metadata with the variant name defined *in that file*.

**Comment by mvahowe** [comment]
We've agreed that "variants are the new publication" and we've explored and clarified that concept on this issue. We've changed the name of "default variant" to source.

There's a PT to add recipes to the derived variant schema (#156).

I suggest that we close this issue and make new, more specific ones as necessary. The most obvious outstanding issue is recipeSpecs (#157).
