### ISSUE TITLE
A better name for "default variant"

### ISSUE THREAD

**Issue by mvahowe** [bible-technology/scripture-burrito#133]
I think "default variant" works, but it sounds like an oxymoron.

(I'd like to keep the word "variant" because, in terms of data representation, the default variant is at the same level as the other variants. Also, however anyone implements this, they need a container for variants, and it's going to be annoying to have to find a word for "variants plus this other thing which looks like a variant but has a different name" in order to name a class or a SQL table.)

The three candidates I can think of are
```
source variant
translation variant
project variant
```
All these terms are overloaded and open to misinterpretation without context, but I think ```project``` works best for me. This variant is the closest SB is going to get to a "Paratext project", for example. It also seems to make sense when describing workflows, eg

```Derived variants for publication are produced from the project variant using recipeSpecs```

Thoughts?

Related to #122

**Comment by FoolRunning** [comment]
I would like to argue against keeping the word "variant" since, although it is on the same level as a variant, it is not a variant itself - it is where the variants get their data. To me, "variant" implies a difference (which means there has to be something to compare with). 

I would, then, suggest just calling it the "source":
``Derived variants for publication are produced from the source using recipeSpecs``

**Comment by mvahowe** [comment]
@FoolRunning I think this could work. Note that, in our metadata, we'll still have

```
"variant": "source"
```

If everyone can live with that cognitive dissonance, let's go with your plan.

**Comment by mvahowe** [comment]
The PR to do this has been merged, so can we close this?
