### ISSUE TITLE
Unicode normalization in textTranslation flavor

### ISSUE THREAD

**Issue by rdb** [bible-technology/scripture-burrito#138]
This is a spin-off issue from #136 and somewhat similar to #137.  The question is whether we want to mandate a particular Unicode normalization form, and if not, whether we need to add a metadata field indicating which normalization procedures have been applied.  We may also want to document recommended practices around Unicode normalization and/or conversion.

This needs to be decided to be able to support PT resources through SB.

**Comment by FoolRunning** [comment]
[Unicode says](https://unicode.org/reports/tr15/#Canonical_Equivalence) that normalization should not make any difference to what is shown on screen to the user and should be treated the same for most comparison operations. However, we have received a few reports that normalization form does make a difference with some fonts. This seems mostly related to re-ordering of the diacritic code-points that happens during normalization. Granted, this is likely a problem with the fonts themselves, but it still "looks wrong" to the end-user and becomes "our problem".

All that to say that the more I think about it, I think we may not want this setting inside of SB as it's not required to read the data. Or, at least, I think this should be a lesser priority and pushed to SB 1.0.0.

Thoughts?

**Comment by rdb** [comment]
I don't have an opinion on the matter, but I might add that there does appear to be an algorithm for detecting the normalization form used in a text (assuming it is applied consistently).  However, it is imperfect (ie. it can result in an indeterminate answer):
https://unicode.org/reports/tr15/#Detecting_Normalization_Forms

**Comment by jag3773** [comment]
We recently ran into an issue where browsers were inserting the pointing in different orders for Hebrew text (of course, Safari was the culprit). This has the unfortunate effect of appearing to look correct to the human eye, but a (naive) string comparison would reveal a mismatch :( Example below for illustrative purposes:

![Screen Shot 2020-02-05 at 2 38 55 PM](https://user-images.githubusercontent.com/107731/75459455-76e08180-594d-11ea-9350-f37a0efe3c2d.png)

So the inverse of @FoolRunning 's comment is also true, sometimes it "looks correct" and still becomes our problem :/ In any case, I think we should address this before 1.0.

**Comment by FoolRunning** [comment]
> sometimes it "looks correct" and still becomes our problem :/

Well, part of the Unicode specification (see my link above) is that string comparisons should be done after normalization in some form. Thus, this should be handled by the applications already (e.g. find/replace in Paratext was missing some text until we normalized the data of both what was being searched and what the user typed in to look for).

**Comment by jag3773** [comment]
Agreed @FoolRunning .  However, if we are transferring these burritos in and out of different VCS systems and processed by different tools the likelihood of a bunch of imperceptible changes being made is high.  In other words, since `git` and presumably other VCS systems don't do comparisons after normalization, we are likely to see a whole bunch of changes for no legitimate reason, making change log comparisons difficult.

I'm happy to move this to 1.0 but I do think that we at least need to record the normalization scheme used so that other applications have a chance of following suit.

Also, would anyone here be flummoxed if we mandated a specific Unicode normalization form?  It shouldn't affect reader applications much, it's just a matter of agreement among writer applications, right?

**Comment by FoolRunning** [comment]
@jag3773, I think if an application depends on normalization, they shouldn't consume the SB without normalizing the data. Also, if my brand new application only works with NFD data and we had the information in SB that said it was NFC, I would expect that my new application would be free to normalize the data into NFD (thus meaning the property in SB really doesn't matter).

**Comment by mvahowe** [comment]
This is not my field, at all, but it sounds to me like maybe we can deal with this by documenting expectations. Is that a viable approach? If so, can someone put some words to those expectations?

**Comment by jonathanrobie** [comment]
W3C recommends NFC for most data on the web.

https://www.w3.org/International/docs/charmod-norm/#choice-of-normalization-form

Any reason we would go a different route?

**Comment by jag3773** [comment]
I'd be happy with documenting NFC as the standard encoding for SB data.  So we wouldn't need anything in the spec just a note in the docs.  Anyone opposed to this?

**Comment by jag3773** [comment]
Latest suggestion is to set the default to NFC but allow for other options to be specified.  Enum:

* NFC
* NFD
* NFKC
* NFKD

**Comment by rdb** [comment]
Will it be optional (or will there be an "unknown" option), or are writers that don't know the normalization form of the text expected to detect and/or normalize it?

**Comment by FoolRunning** [comment]
@rdb, To clarify what we decided, we're going to assume NFC if nothing is specified, but allow it to be explicitly specified as one of the above values. 

I think this means that the creators of the SB will have to ensure that they write the data out in the correct form. Hopefully the writers know the normalization of the data they are writing or can normalize it while writing it. I can't see how "unknown" could be useful since this is specifying the normalization of the data in the SB, not necessarily (but it could be) as it was in the application before it was put into a SB.

**Comment by mvahowe** [comment]
I think PR #177 implements this
