### ISSUE TITLE
Parsing Bible references

### ISSUE THREAD

**Issue by mvahowe** [bible-technology/scripture-burrito#139]
Thinking about the plan to use USFM rather than USX for default variants, the problem I keep coming back to is machine-readable references. USX provides these in an optional "loc" attribute. This feature is widely used to enable the generation of hyperlinks, regardless of the localized reference format. The localized formats are extremely variable and, in my view, impossible to guess accurately.

Putting the equivalent of \@loc into USFM makes no sense, since it requires translators to maintain the information in a non-localized format. This would make every reference twice as long, would require training, and humans are generally bad at keeping duplicate information in sync.

One solution is to use USX everywhere.

The other solution, which I think we should consider, is making the parsing rules of localized references explicit in SB. Paratext handles this via a formidable form where the reference syntax is specified, and then uses this information in "Paratext Checks".

If we represented this information in a portable format, and if we provided reference parsing code (which is not especially complex given all the parameters), machine-readable references could be generated anywhere as needed. Also, references could be checked.

**Comment by mvahowe** [comment]
@FoolRunning says the relevant PT settings file values are
- SegmentOrder
- RangeIndicator
- SequenceIndicator
- RefsMustMatchVerseSegments
- SegmentsMustHaveFinalPunctuation
- NoSpaceBetweenBookAndChapter
- OriginRangeOption
- ChapterVerseSeparator
- ChapterRangeSeparator
- ChapterNumberSeparator
- BookSequenceSeparator
- BookSourceForMarkerXt
- BookSourceForMarkerR
- ReferenceExtraMaterial
- ReferenceFinalPunctuation

We also need the abbr names from the SB names section.

**Comment by FoolRunning** [comment]
Just to parse the references (i.e. not validating them), I think we can remove **OriginRangeOption**, **SegmentsMustHaveFinalPunctuation**, and **RefsMustMatchVerseSegments**.

And to describe what each thing is:
- **NoSpaceBetweenBookAndChapter** (whether there is a space between the book and the chapter number)
- **ChapterVerseSeparator** (character(s) used between a chapter and a verse)
- **RangeIndicator** (character(s) used to indicate a range of verses)
- **SequenceIndicator** (character(s) used to indicate a list of verses)
- **ChapterRangeSeparator** (character(s) used to indicate a range of chapters)
- **ChapterNumberSeparator** (character(s) used to indicate a list of chapters)
- **BookSequenceSeparator** (character(s) used to indicate a list of books)
- **ReferenceExtraMaterial** (words/characters that can appear before or after a reference)
- **ReferenceFinalPunctuation** (character(s) used to mark the end of the reference)
- **BookSourceForMarkerXt** (name category - abbreviation, shortname, longName - to use for validating **\\xt** markers and equivalent)
- **BookSourceForMarkerR** (name category - abbreviation, shortname, longName - to use for validating **\\r** markers and equivalent)
- ~~SegmentOrder~~ (turns out this is used for the chapter/verse check and not for references)

**Comment by FoolRunning** [comment]
And just to scare everyone, this is an example of a regular expression that Paratext creates to parse references in a project:
`
(?<wholeRef>(?<extra1>(Sapta\ |\s?))(?<book>(?!(\ ko\ ))1SA|2SA|1AT|2AT|1EG|2EG|1KO|2KO|1TE|2TE|1TI|2TI|1PI|2PI|1JO|2JO|3JO|\d*(((?!Sapta\ |-)\s*[^\d\s\p{P}\p{S}])+))?((?<bookChapSep>\s*((?!-)[\p{P}\p{S}])*\s*)(?<chap>\d+((?!Sapta\ |-)[^\d\s\p{P}\p{S}])*)((?<chapVersSep>:|\s*((?!-)[\p{P}\p{S}])*\s*)(?<vSep>)(?<verse2>)(?<verse1>\d+((?!Sapta\ |-)[^\d\s\p{P}\p{S}\ ko\ ])*)((?<vSep>,|\s*((?!-)[\p{P}\p{S}])*\s*)(?<verse2>\d+((?!Sapta\ |-)[^\d\s\p{P}\p{S}\ ko\ ])*))*)?)?(?<extra2>(Sapta\ |\s??)))((?<majorRangeSep>\s*-\s*)(?<wholeRef>(?<extra1>(Sapta\ |\s?))(?<book>(?!(\ ko\ ))1SA|2SA|1AT|2AT|1EG|2EG|1KO|2KO|1TE|2TE|1TI|2TI|1PI|2PI|1JO|2JO|3JO|\d*(((?!Sapta\ |-)\s*[^\d\s\p{P}\p{S}])+))?((?<bookChapSep>\s*((?!-)[\p{P}\p{S}])*\s*)(?<chap>\d+((?!Sapta\ |-)[^\d\s\p{P}\p{S}])*)((?<chapVersSep>:|\s*((?!-)[\p{P}\p{S}])*\s*)(?<vSep>)(?<verse2>)(?<verse1>\d+((?!Sapta\ |-)[^\d\s\p{P}\p{S}\ ko\ ])*)((?<vSep>,|\s*((?!-)[\p{P}\p{S}])*\s*)(?<verse2>\d+((?!Sapta\ |-)[^\d\s\p{P}\p{S}\ ko\ ])*))*)?)?(?<extra2>(Sapta\ |\s??))))*(?<final>(\s*((?!-)[\p{P}\p{S}])*\s*$)?)
`

I'm hoping, since we're not doing validation, we can make this much simpler in SB. 😄
