### ISSUE TITLE
Make `metadata.json` name and location clearly mandatory

### ISSUE THREAD

**Issue by jonathanrobie** [bible-technology/scripture-burrito#252]
> A Scripture Burrito can exist in multiple data formats. By convention, when the metadata is written to disk it should be in a file with the name of `metadata.json` at the root level of the Burrito.

By convention?

Is the name `metadata.json` required?  Must it be at the root level?  The language is not clear about whether this is a hard requirement.  I think it should be.

**Comment by jtauber** [comment]
Agreed, I think it should be a hard requirement. Also "can exist in multiple data formats" seems wrong too (or at least requires clarification)

**Comment by jtauber** [comment]
Given that `metadata.json` contains explicit links to the ingredients in a burrito, knowing where the `metadata.json` file is located is sufficient to locate a burrito.

I can think of (at least) three scenarios:

## 1. Directory 

The `metadata.json` file and the ingredients are in a directory. In this case, as long as the `metadata.json` file is so-called and lives directly in that directory, then locating the directory is actually sufficient to locate the burrito. The ingredients can be organized in subdirectories but do we want to say anything about the ingredients having to be in this directory tree and not located "outside" (via a .. path, etc) ?

## 2. Archive File

Same as above but the "directory" is compressed as an archive file. If uncompressed. `metadata.json` would be at the top-level and all the references to the ingredients work out. In this case obviously the ingredients DO need to be in the directory tree. Do we want to restrict the particular archive format? ZIP, TAR, ... Or at least make minimal requirements for compliance?

## 3. Web

In this case (assuming we want to mention it) what we actually need is just the URL of the `metadata.json` and the ingredients will contain other resolvable URIs. Should we even talk about this scenario? In some senses this is a superset of 1 given `file:` URLs. But perhaps this is the only scenario in which we allow for "external" ingredients (because all ingredients in this scenario are effectively external)

**Comment by jag3773** [comment]
@jtauber said:

>Given that metadata.json contains explicit links to the ingredients in a burrito, knowing where the metadata.json file is located is sufficient to locate a burrito.

That needs to go into the docs.

For the questions:

1. By convention all files should be in the same directory as metadata.json or sub directories. An acceptable exception is large media files that you may not want to distribute with the burrito itself, in which case an URL is acceptable. A burrito is intended to be a snapshot so maintaining external resources is beyond the scope of this specification.

2. Let's only support `.zip` files.

3. Couple options:
  - Github repository is legit, a particular burrito would be a specific commit or tag. The repository itself is technically a project with multiple burrito snapshots in it. (For example, see https://github.com/bible-technology/sb_textStories for the project, or https://raw.githubusercontent.com/bible-technology/sb_textStories/master/metadata.json for the latest burrito, or https://raw.githubusercontent.com/bible-technology/sb_textStories/v4/metadata.json for verrsion 4 of the burrito).
  - Given a url to a `metadata.json` file, software should be able to download all of the referenced files.
