### ISSUE TITLE
Flavor Specific Schema details

### ISSUE THREAD

**Issue by jag3773** [bible-technology/scripture-burrito#26]
Needed for each of these

* [x] Scripture text
* [x] Scripture audio
* [x] Scripture sign language video
* [x] Scripture "ready to print"
* [x] Scripture braille
* [x] Gloss parascriptural flavor related to #14 and #15
* [x] Word alignment parascriptural flavor related to #14 and #15 
* [x] Versification peripheral flavor related to https://github.com/ubsicap/versification_json

**Comment by jonathanrobie** [comment]
I think it would be really helpful to have a crisp definition of what a flavor is and how we choose which ones are needed.

For instance, if I have a scripture plus a lexicon, is that a new flavor?   What if I add maps?  Is a study Bible a new flavor?   Is a sign language video a different flavor from a Jesus film?   Do we really think we can anticipate all of these things?

**Comment by jonathanrobie** [comment]
Do we create a flavor when there is an interoperability need, e.g. two or more parties have implementations that support video?

**Comment by mvahowe** [comment]
> I think it would be really helpful to have a crisp definition of what a flavor is

https://docs.burrito.bible/en/latest/concepts.html : "Burritos exist in a number of flavors. A flavor describes a way to represent one class of entity as a burrito. Each flavor corresponds to a high-level entity, such as a Scripture text project or a sign language dictionary. A flavor specification typically includes ingredients with multiple mimetypes."

Here, and everywhere else in the documentation, I'm very open to PR suggestions of how to make things crisper and clearer.
 
> For instance, if I have a scripture plus a lexicon, is that a new flavor?

Personally, I'd argue for representing that as a relationship between two burritos of two different instances (assuming that "lexicon" is something that could potentially be used independently of the text it is being distributed with.)

> What if I add maps?

If it was "a pile of maps that relate to the Bible in general" then I'd see that as three burritos (text plus lexicon plus maps). If it was maps that somehow related to the detail of text in one specific translation, I think we'd be talking about

> a study Bible

and we already store those as a single entry within DBL.

It's possible to argue the toss in some cases, but I think the rule of thumb is "divide things down to the lowest level that makes sense, and no lower, to minimize complexity and maximize reusability".

> Is a sign language video a different flavor from a Jesus film?

Yes, absolutely. Sign language has specific metadata needs, for example. I'd expect significant similarity between all video flavors, but also significant differences. For example, Deaf Bible Society currently maintains that we should require a dictionary (such as SOOSL) with sign language projects. That clearly makes no sense for vanilla "film" content.

> Do we really think we can anticipate all of these things?

No. It's going to be an evolving standard. But I think we can nail down the most common cases quite easily, and that there's some low-hanging fruit beyond what DBL and PT currently support.

In the short term, there's an overhead to fiddling with metadata, and with attempting to place diverse content types under one overarching structure. For one coder who is used to rolling her own files and writing her own code to process it, this may seem like a waste of time. Where I think this approach pays dividends is for libraries (like DBL) and for toolchains that potentially consume data from multiple sources with little or no human intervention.

Also, while data exchange is obviously one of our goals, our current approach also helps even within one organization that handles multiple types of content. So, eg, imagine a future edition of PT or PA that supports, eg, linking written text to the Jesus Film. Supporting video is obviously going to require new code but, if SB works out the way I hope, PT could download the video burrito using exactly the same code as it would use for any other DBL-like resource. It could display the name, date, language and copyright of that video using existing code. And so on. That seems to me to be a huge win, because it lowers the barriers to experimentation with all kinds of "mash up".

**Comment by jag3773** [comment]
Can we move the discussion about
>I think it would be really helpful to have a crisp definition of what a flavor is and how we choose which ones are needed.

to issue #51 please?

**Comment by mvahowe** [comment]
We now have example documents for each of these flavors that validate as x-flavors. (In other words they work as instances of the correct flavorType, with no validation of the flavorDetails section. The next steps are

* Remove the x- which means writing each flavorDetails into the schema

* Documentation.

**Comment by mvahowe** [comment]
We now have a schema, example document and documentation for scriptureText and scriptureAudio, in the current PR. I made a separate issue to discuss scriptureText. Any comments on scriptureAudio (which is much simpler) welcome here!

**Comment by mvahowe** [comment]
We now have a schema, example document and documentation for scriptureText and scriptureAudio, in the new "develop" branch which can be browsed at https://docs.burrito.bible/en/develop/

**Comment by mvahowe** [comment]
Marking word alignment as done, here, since the remaining work for now is covered by another issue.

**Comment by mvahowe** [comment]
Marking Bible story gloss as done here, pending a new issue for matters arising.

**Comment by mvahowe** [comment]
Marking versification as done here, pending feedback from CA.
