### ISSUE TITLE
Fix ajv Validation

### ISSUE THREAD

**Issue by jag3773** [bible-technology/scripture-burrito#260]
In the example repos, please fix the ajv validation.

**Comment by jtauber** [comment]
After some investigate, the issue is that ajv 7.0.0 (we're now on 8.3.0) introduced strict mode.

There seems to be (at least) two things failing:

1. use of the unknown keyword `$$target`
2. use of the unknown forrmat `date-time`

Both of which I've been investigating (although I can get validation to pass by turning of strict mode, this is suboptimal).

**Comment by jtauber** [comment]
Turns out `$$target` is a Spinax extension.

**Comment by jag3773** [comment]
May have to do with our sphinx json-schema documentation plugin, right?

**Comment by jtauber** [comment]
Yes. I'm working on making `$$target` allowable without relaxing any other strict checks.

**Comment by jtauber** [comment]
I had to make substantial changes to the schemas to get them to pass in strict mode.

I suspect there were a lot of changes to the schema language itself and things were silently failing before.
