### ISSUE TITLE
Suggestion: Machine-readable field in licenses

### ISSUE THREAD

**Issue by rmunn** [bible-technology/scripture-burrito#292]
It might be useful for the `copyright` section of metadata.json to include a machine-readable property, similar to [how the `license` field of NPM's `package.json` works](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#license). I suggest a property named `spdx` to go alongside `url` and/or `ingredient`, which would be defined to contain one of the short license codes on [the SPDX list](https://spdx.org/licenses/), e.g. `CC-BY-4.0`. The property would be optional, as not every resource would be licensed under a well-known license like CC. But for those that are, it would allow use cases like "I want to automatically download any resources in language X that are either public domain or under a license allowing use for free". The software would be able to use the `spdx` field to automatically determine that certain resources were under a free license, without needing a human-input step.

**Comment by jag3773** [comment]
Hi @rmunn -- as we looked into this previously it seemed that Creative Commons preferred to have the full URL to the public license, which in the case of CC includes the clauses and versions, e.g. https://creativecommons.org/licenses/by-sa/4.0/ . The suggestion is that these be included in the `url` field whenever a public license is being used. The same appears to be true of other content licenses, such as the ODbL: https://opendatacommons.org/licenses/odbl/1-0/.

Since we are working with content and not code, that seemed like the most reasonable approach as we don't need to support the myriad of software licenses that are out there. This approach further allows for any publicly available license to be linked to, without having to be on a particular list.

In any case, that was the rationale for the approach that we took. Do you think this approach meets your needs or are there features missing from your perspective?

**Comment by shadow-light** [comment]
For our platform, I've been scrapping pages looking for CC URLs to identify the license. So as long as they use standard CC URLs then those can be auto-detected pretty easily.

My fear is that some people (or a lot of people) are going to put in a URL to their website that contains the license or an explanation of the CC license they are using. You also have to account for some people using "http" rather than "https" or missing the trailing slash etc. There is also multiple URLs for the same license, e.g.:

- https://creativecommons.org/licenses/by-sa/4.0/
- https://creativecommons.org/licenses/by-sa/4.0/legalcode
- https://creativecommons.org/licenses/by-sa/4.0/legalcode.de

So I'd prefer an optional `spdx` field is added as @rmunn suggests, and for that to be recommended over a URL whenever possible.

**Comment by shadow-light** [comment]
Any further thoughts on this? This is a really important field as more and more translations move to public licenses, and a variety of them.

**Comment by shadow-light** [comment]
Agreed with @rmunn , and I'll add that this isn't hypothetical. This is a huge problem for [the Bible platform](https://fetch.bible) we're working on. We have to parse thousands of translations and while a wrong title or language can be annoying, a wrong license detection makes us liable to litigation....

**Comment by jonathanrobie** [comment]
I am reopening this in light of the previous two comments.  Would it be possible to have a Zoom meeting to discuss some time next week?  I want to make sure your needs are addressed, I need to have a better understanding.

**Comment by shadow-light** [comment]
Thanks Jonathan, that would be great. Due to my timezone, the earlier the better US time.

**Comment by shadow-light** [comment]
Here's what I came up with in making licences machine readable:

```ts
export interface MetaRestrictions {
    /* Restrictions that (1) commonly apply to translations and (2) commonly affect users

    These are designed to aid automated selection/elimination of translations for most use cases
        but are not exhaustive and users will still need to take responsibility themselves for
        appropriately using/not using translations.

    If there are complex interactions between conditions
        e.g. Verse limitations apply to commercial use but not other uses
        Then create multiple custom licenses to account for the various possibilities

    Not all conditions are included
        For example some translations forbid unchristian use
            e.g. https://ebible.org/Scriptures/details.php?id=ukr1996
        But such conditions are too vague and varied to usefully categorise and this service is
        already expected to be almost exclusively used by mainline Christians.
        If a condition _is_ "likely" to affect users then the `forbid_other` should be true.

    */

    // Limit on how many verses can be quoted in a single "work"
    // NOTE Inclusive (1000 means 1000 is ok but 1001 is a violation)
    limit_verses:number|null

    // Limit on how much of a single Bible "book" can be quoted
    // NOTE Inclusive (50 means 50% of book is ok but 51% is not)
    limit_book_ratio:number|null

    // Limit on how much of the total "work" can be made up of quotations
    // NOTE Exclusive (50 means 50% is a violation but 49% isn't)
    limit_content_ratio:number|null

    // Commercial use is forbidden
    forbid_commercial:boolean

    // Modifying the text is forbidden either entirely or if publishing under a different license
    forbid_derivatives:boolean|'same-license'

    // The owner of the translation must be attributed whenever the text is used
    forbid_attributionless:boolean

    // Other conditions that are significant enough to potentially be an issue for some users
    // NOTE Licenses will always have slight variations so this should only be used if "significant"
    forbid_other:boolean
}
```

If we don't go with a field identifying the license, this could be an even better option.

**Comment by jonathanrobie** [comment]
In today's meeting we decided the following:

- A simple way to search for permissions would be very useful in publishing systems - but we haven't really addressed those needs in Scripture-Text, and can't really do that before 1.0 is out.
- Doing this right requires lawyer involvement and time.  This might make the most sense in conjunction with the DBL or the TRE, which would need to be involved in designing the solution.
- If the field is required, then many burritos will not be possible because people do not know what values to provide.  If it is optional, it probably won't be used and many valid resources will be missed. We may want to explore ways to require it at certain points in systems like DBL or TRE, but again, this is out of scope for SB 1.0, and would need significant time to reach sufficient agreement and get the lawyers to sign off.

**Comment by shadow-light** [comment]
Fair enough, glad it's still in consideration
