### ISSUE TITLE
Can we assume one DBL?

### ISSUE THREAD

**Issue by jonathanrobie** [bible-technology/scripture-burrito#38]
In today's call, we were operating under the assumption that there is no central naming authority.  Could DBL serve as a central naming authority?  I have been assuming that we plan to have one DBL, not many, and that assumption is found in some parts of our documentation: 

https://docs.burrito.bible/en/latest/history.html#new-media-new-ecosystems

> While Paratext will continue to upload much of the text content of DBL, uploading of other entry types is now handled by Nathanael, an application developed by the DBL team. Bible text editors such as Autographa and translationStudio are being developed to meet the needs of teams with modest language and technology skills. Groups such as unfoldingWord, Wycliffe Associates and Faith Comes By Hearing are developing ecosystems for users of their own systems. This is the context within which the ETEN Bible Tools committee identified a need for data exchange formats, leading to Scripture Burrito.

But in other places our documentation does not seem to assume a single DBL:

> Scripture Burrito assumes the existence of ecosystem servers that provide ids for users, organizations and projects, and stores information to enable that server-hosted context to be discovered.
> 
> Scripture Burrito is intended to allow lossless roundtripping of projects between ecosystems. This depends to some extent on references to ecosystem servers that enable reconnection with different ecosystem-specific contexts.

That description seems to imply that there might be multiple co-equal DBLs.   If that's the case, we have other problems to solve if we want to have a good overview of what is available and how it is licensed.

Which is ETEN asking us to do?  This needs to be clear in our documentation.  It may inform how we approach things like identifiers.

**Comment by jonathanrobie** [comment]
To me, this is really a question about **silos** versus **building a community**.

DBL is designed to include Scripture from many sources, providing an overview that lets the translation community and donors see the current status and which needs are most acute, shows people who want to use Scripture who holds the copyright so they can negotiate, etc.

If DBL is just another silo, we would need to build something else for federated searches across silos.   But the whole purpose of DBL is to be that shared space.

Do we agree on that?  If not, is there any notion of a shared space that we are trying to build together?

**Comment by jag3773** [comment]
Also from the [docs](https://docs.burrito.bible/en/latest/use_cases.html), 
>Scripture Burrito is designed first and foremost for data interchange between ecosystems...

Nothing in SB is meant as a replacement of DBL, nor is anything in SB intended to take away from DBL. On the contrary, it's intended to make it much simpler for developers to get data into and out of DBL.

The conversation is important in terms of discoverability of projects, which has come up from time to time. Once we have SB defined and in place, it becomes straightforward to get projects in and out of systems and a conversation around discoverability is likely to get much more traction. In other words, once we have a common data format, it becomes easy to standardize servers/apis on that.

Another note is that most projects start in other ecosystems because DBL is focused on archival and distribution of Bible translations. Further, the SB scope of resources is much larger than the (current) DBL scope of only Scripture. I can't speak for their long terms goals but I don't think anything in the `peripheral` flavor would be added to the DBL.

**Comment by jonathanrobie** [comment]
Here's one way to position this:

1. For Scripture (source language texts and translations), SB allows applications in the DBL ecosystem to exchange data with DBL and with each other.  DBL makes these resources discoverable.  We should think about how the lifecycle of identifiers relates to this.

2. For things that do not look like Scripture, we have the same discoverability needs that DBL addresses for Scripture.  The Copenhagen Alliance needs to look at interoperability and discoverability for these resources.  Since all of these resources are related to Scripture, should we discuss whether we need a place in DBL for these as well?  Or something else like DBL?

**Comment by mvahowe** [comment]
@jonathanrobie On that specific proposal, it seems to me that, on the one hand, we lose the benefits of having everything linked to a single place and, on the other hand, we don't get the flexibility that comes with supporting an arbitrary number of reference servers.

The scope of SB ended up being very large indeed, so I think it would be a stretch to imagine that anything anyone could ever represent as a SB would make sense within DBL. There's also the issue that DBL has policies that might prevent some organizations from joining (eg if there are unresolved conflicts with one of the major stakeholders.) I think that's entirely reasonable. What wouldn't be reasonable is for DBL to be able to effectively stop such organizations from translating Scripture, which might be the unintended corollary of making DBL the sole reference for everything.

Personally, I think that software design should be apolitical. I think there are some issues that do need to be worked through, maybe by people above my pay grade, but I don't think we need to try to anticipate such policies in how we design SB.

**Comment by jonathanrobie** [comment]
There is a set of things that DBL is prepared to handle and that DBL consumers can understand because they are in well-defined formats.  The benefit of seeing beyond individual silos is very important, and that's what DBL does for these resources.

We don't (yet) have an equivalent for other formats.  There is no interoperability story for an arbitrary proprietary format, and we have no discoverability story for things that are not in DBL.  These are things that the Copenhagen Alliance might look at, we may try to persuade DBL to accept more kinds of data, we may want to come up with standards to allow a wider variety of data to be used interoperably (again, something the Copenhagen Alliance might be involved in defining).   But I don't think merely accepting any proprietary format is enough for either interoperability or discoverability.

I agree with you that software design should be apolitical.  Or more precisely: we are designing software to encourage collaboration and sharing, two very political activities.  Clearly, we dont' want to stop anyone from translating Scripture, but I don't think there is any danger of that.  If there is, let's flesh out the use cases and requirements that we need to satisfy to avoid doing that.

**Comment by mvahowe** [comment]
I think that, for a lot of possible future SB flavors, it will be very hard to persuade DBL to be involved. That's not about how proprietary the format is, it's about how much like Scripture the content is. It's the Digital Bible Library, not a Digital Christian Library. I think the Bible translation world needs collaborative options that don't depend on policy changes at DBL.

I also think that we need "more than one DBL" just to handle the existence of Paratext servers. There are certainly things that DBL and PT should be doing the same way, but there are also things that should remain different, often because DBL and PT are publication and translation-facing respectively. Designing things to assume that DBL is the centre for everything seems awkward to me even when just dealing with Paratext. For example, there may be translations in Send and Receive that should not be circulated any wider than necessary. Two servers doubles the risk of exposure (potentially with life-changing consequences for the translators).

**Comment by klassenjm** [comment]
@mvahowe On your second paragraph -- I'm not sure I understand something. It seems like you're referring to other servers like Send / Receive as other "DBL"s (?). I don't think anyone is assuming or suggesting that a translation project in process (on Send / Receive for example) is automatically (also) stored in DBL. It could be, as you know, and often is, but normally as a step taken when the project owner identifies that some / all of the project content is 'publishable'.

I'm sorry if I'm missing something - I know I have not been engaged in the dialogues happening here.

**Comment by jonathanrobie** [comment]
@mvahowe I don't understand what you mean when you say we need more than one DBL to handle the existence of Paratext servers.   I don't think that Paratext servers do the same thing as DBL.  

For Scripture, at least, I think there is only one DBL.  It gives an overview of the status of translation everywhere, across our silos, whether or not people use Paratext.  It also tells you who owns the license and whether it is freely licensed (getting this last part right really matters, there is more to do here).    I don't think it makes sense to have multiple parallel DBLs, if we do that then we have created a set of silos and we need to invent another DBL to help us see what is in the various silos.  The problem turtles if someone chooses not to be part of the new meta-DBL.

The Paratext servers are not DBL, they have a different purpose - providing a platform for collaboration and sharing.   That includes freely sharing many resources with translators even if they are not freely licensed for everyone.   These servers can be used by other clients, but other translation clients can choose to store their data in other places, such as GitHub, and may not be interested in content that is not freely licensed.   This is one place that we really need to allow for multiple ecosystems at the same level.

But we also need to provide for things that do not fit in DBL.  That's important.  The Copenhagen Alliance needs this, and it needs interoperability for these resources.   We also need to discuss discoverability.  Saying that something belongs to the `peripheral` flavor doesn't really address these requirements.

I would really like to see use cases for all of these things, and careful consideration of how these various systems work with various roles in the user community.   (I won't be at the meeting this week, sorry, I am on vacation.)

**Comment by mvahowe** [comment]
@jonathanrobie @klassenjm "One DBL" was not my choice of vocabulary, and I think it's ambiguous. The distinction that I think we need to make is something like the difference between git (an open source program that anyone can use however they like, and which provides consistent interfaces) and GitHub (one particular instance of git, plus some closed-source code that, together, drives the biggest git-powered community.)

There is clearly "only one DBL" if only because I'm sure UBS and/or ETEN think they own that name. Right now, DBL has a unique software stack, but I don't think that's what makes it unique. (There's really nothing that DBL does that is a huge technical challenge, it's all relatively standard CRUD server stuff.)

What makes DBL unique is surely the community of organizations who have chosen to place their content in DBL. DBL without those organizations would be one more Bible enthusiast website. It's not the technology that makes DBL unique. (I often think that DBL occupies that position in spite of some of the technology.)

I'm not suggesting that anyone should be working to set up a dozen DBL competitors. (That could happen, I don't think that obfuscating Scripture Burrito would slow down anyone who wanted to do that, and I think that the formidable challenges are on the level of organizational buy in rather than in writing code.)

What I've been saying from the very first document I wrote for this group is that portability requires formats, but also interfaces. Right now DBL has a unique API. That's not a feature, it's a total pain for anyone who wants software to work with both DBL plus anything else. Consistent interfaces are A Good Thing. That's why we have TWAIN for scanners and PCL and Postscript for printers. That's why we all use a convoluted protocol called TCP/IP to connect any two computers for any reason, rather than point to point connections using some bespoke protocol like we did in the 80s. (We use TCP/IP even though point to point had some undeniable technical advantages such as security and QoS. That's how much interfaces matter.)

If we strip DBL back to the bare technology it is (among other things) a way to store, upload and download Scripture-related content. Paratext has one of those too, but everything about it works a different way. Some of those differences are for good reasons. Many of those differences are accidental, historical or just plain perverse. As a result, it's incredibly hard for anyone to write a third-party application or website that exchanges content with both DBL and the Paratext ecosystem, because much of the code has to be written twice, and then maintained. I'm telling you that there's no way to spin that as a feature, unless the Tower of Babel was a really neat idea to improve international cooperation.

So yes, there's one "thing" called DBL, and I don't expect that to change. But DBL is also one instance of a class of servers that do similar things for the Bible translation and publishing world. As far as I'm concerned, servers within that class should do similar things in similar ways. That saves time and money writing the code in the first place, and it encourages higher adoption of all servers, including DBL, as well as allowing reuse of clients such as as Nathanael.

In that sense, Send and Receive is "another DBL". Or, if you prefer, DBL is "another Send and Receive". And Unfolding Word, Faith Comes by Hearing and other organisations already have products in that space. In that sense, DBL and Send and Receive are "another Faith Comes by Hearing". All I'm saying is that, on a technical level, it would be nice if the servers in that space offered a similar interface for similar operations. That doesn't mean every website becomes DBL. It just means that the next generation of techies will waste a lot less time, that new initiatives will happen faster and that more data will be shared.

**Comment by mvahowe** [comment]
Some real issues (mainly overheard at the BT conference in Dallas earlier this year) that the above scenario addresses...

* API.Bible's digital publishing tool could work from DBL, as at present, for published work, but could also work from PTX, for work in progress that DBL is not ready to receive. Right now, the options are to force unfinished work into DBL or for API.Bible to run two parallel toolchains.

* Publishing Assistant could use texts from DBL, which makes a lot of sense if the text has been licensed. I'm not going to try to describe what happens now, let alone some of the workarounds I heard, all because DBL and Send and Receive are incompatible on every level.

* Scripture App Builder could work with DBL texts.

* Another instance of YouVersion could work with unpublished texts.

* Glisten could use text from either DBL or PTX. (They used to do one, now they do the other, and the choices seem to be on less than solid technical grounds.) They could get audio files from DBL or FCBH or Biblica and mash them up with text from DBL or PTX or Unfolding Word, all with the same codebase.

* Collecting aggregate data about both translations and publications, eg for progress.bible, would be way easier.

And so on.

**Comment by mvahowe** [comment]
And, to get back to what I think was the specific conversation that sparked this conversation, I think it would be a big mistake to design Scripture Burrito with the assumption that DBL will provide all the ids for every Scripture Burrito document in the world because

1. I don't think DBL is looking to take on that amount of work
1. It makes working without an Internet connection harder
1. It makes intranet and test scenarios harder (ie are we going to have dev builds of "The One DBL" so that third-party developers have a way to test their code without connecting to DBL? Wouldn't that be completely surreal?)
1. It either means that DBL has to say "yes" to every request for an id or, alternatively, DBL becomes the gatekeeper for any technology using Scripture Burrito, with the power to lock translations or organizations out of any SB technology just by refusing to grant an id.
1. Either way, DBL then needs some sort of id conflict resolution procedure...

I liked the idea of a delegated URN scheme as discussed previously, but that idea was rejected last week. The only sane alternative I see is supporting arbitrary id servers, and assuming/hoping that common sense and/or Christian virtue will prevent 1000 of these from competing for world domination.

If we wanted a centralized id scheme (and there are certainly technical arguments for that), I don't think it's helpful for tha centralized id scheme to be called DBL.

**Comment by jonathanrobie** [comment]
I don't think that DBL should create all IDs for all systems.  I do think DBL could maintain a registry of prefixes that are recognized for names so that we do not have multiple parties using the same prefix. A delegated ID scheme is good, but a prefix registry makes it better.

I also think it would be good for our documentation to be clear that SB is being designed for systems to exchange data with DBL and with each other and to provide use cases.  And maybe we should have lists of use cases - is there a place to submit them?

**Comment by mvahowe** [comment]
I think that a prefix registry is a good idea, which we have discussed before. I don't think that DBL should be the place where that happens. In a sense, the place where that happens right now is the Scripture Burrito schema which has a whitelist of prefixes. If we want a prefix registry and a process to declare prefixes, that sounds to me like a new server that ought to be independent of DBL and PTX and everyone else.

Also, if that's what we want, why wouldn't we make the curated prefix system a URN?

**Comment by jonathanrobie** [comment]
I don't think we can update the Scripture Burrito schema whenever someone registers a new prefix, and that would require the SB group to approve the change.

What is the advantage of having a new server that is independent of DBL for this purpose? If prefix clashes occur, they will occur in DBL.  If people are not putting their texts into DBL, clashes will not be seen.

For non-Scripture resources, we may need an additional solution.  But I really hate to standardize that solution before we work through the use cases and requirements.  And I think that has to include the broader Copenhagen Alliance community. Right now, that part of the spec looks like hand waving to me.

**Comment by mvahowe** [comment]
A lot depends how fast prefixes move. I'm expecting initial updates to the Scripture Burrito schema to happen quite regularly for a while, and I'd expect to have most of the organizations we know covered before 1.0. We also have an x- feature which means that organizations can literally make stuff up while waiting for an update.

We can, of course, remove the whitelist from the schema, but then we can't use the schema to validate the prefix, or indeed the org-dependent part of the id. (Right now the DBL schema does check that, eg, a Biblica ID looks like a Biblica ID.)

Prefix clashes can occur anywhere. They could happen in PT Reg. You seem to be assuming that DBL acts as a hub, but it really doesn't. There are probably hundreds or thousands of entries in Send and Receive that have not made it to DBL. I can't imagine Autographa and BTI ever sharing word alignment information via DBL. Maybe the problem is the name DBL, which suggests that it's The (one true) Digital Bible Library. That's not the current reality and I can't see it ever becoming the reality. In Bible lifespan terms, PTReg is much closer to the centre than DBL.

The advantage of an independent server is that it's independent (or, more realistically, that there's an intentional form of governance that is acceptable to all parties.) This is really an issue for @klassenjm  but I can't see UBS wanting to end up having to arbitrate between, say, SIL and Unfolding Word on prefixes or anything else. One of the benefits of the URN route was that it would have imposed a "seen to be fair" process. Not taking the URN route doesn't let us off the hook - we still need to tick the "seen to be fair" box.

Also, on a technical going-on trend level, micro-services are currently preferred over "do it all" monoliths. An independent prefix service would do one quite simple thing, and it ought to be able to do it in a highly scalable and redundant way, with no possibility of, eg that service taking the entire Bible ecosystem down because a Digital Academy workshop is DDoSing DBL with uploads.

**Comment by mvahowe** [comment]
(Which bit of the spec is "hand waving"? Last time I looked it spelled out very clearly how ids are constructed, and all the options are currently in the schema. That seems quite specific to me.)

**Comment by jonathanrobie** [comment]
> The advantage of an independent server is that it's independent (or, more realistically, that there's an intentional form of governance that is acceptable to all parties.)

This is precisely my point.  DBL has a system of governance.  If we set up an independent server for this purpose, we need to create a system of governance for it.  You can't get around the need for a form of governance.

If we want to work together well, we need systems that go beyond our individual silos.  Putting something in GitHub does not make it discoverable in an organized way or help people get an overview of what is out there.  Any system we create for this purpose will require a system of governance that is acceptable to the people who use it.  There will always be someone who chooses not to participate or needs to be excluded for some important reason.  We want to include as many people as we can.

So if we create a new server with a new system of governance, why would we expect its governance body to be better than ETEN or the Copenhagen Alliance?  Why not use existing organizations for this?

**Comment by mvahowe** [comment]
I can't comment on Copenhagen Alliance. I'm pretty sure ETEN doesn't want to directly run anything on this level. DBL governance is pretty much UBS, and that seems to fine for me as long as everything is going fairly well. It's obviously not fine at all if there's a conflict between UBS and another organization. I think PTX has more independent governance than DBL.

**Comment by klassenjm** [comment]
PT governance is the Paratext Alliance, which is UBS and SIL, but which actively tries to include and process input from all Paratext users and using organizations. This is via the Paratext BoG in which there are members of SIL and UBS. The DBL governance is less clear -- but primarily in terms of decision making around application process (to contribute or request content) it has been more broad. It is not just UBS. It has been through the PCC (Partnership Credentials Committee), which is composed of representatives from UBS, SIL, Seed Co, Biblica, ETEN, (at least, and maybe another).

At this moment in time, I think the role and function of PCC will likely be reviewed and considered, to determine what serves needs best, and what serves the function of DBL best.

I'm not pointing any conclusions. I don't have one because in many ways this is my first real attempt to understand what this group is talking about wrt ID servers etc.

**Comment by jonathanrobie** [comment]
If that's true, that may be an indication that we need more governance for DBL.  And maybe that's worth discussing with ETEN, given the importance of DBL.

> (Which bit of the spec is "hand waving"? Last time I looked it spelled out very clearly how ids are constructed, and all the options are currently in the schema. That seems quite specific to me.)

For DBL content, I can see how to get to a set of unique IDs that do not clash and an overview of what is out there.

For other things, I don't see what that picture looks like yet.  We will have the same need for discoverability.  If we are trying to create sets of materials that translators and scholars can use, it will also be useful to have an overview of who is working on what and how far along it is.

Also, the `peripheral` flavor gives us an extensibility point, but not a framework for interoperability.  We need a way to specify formats and stylesheets and reference systems and such.  That is very much in the purview of the Copenhagen Alliance.

If all we are doing is defining an archive format with a manifest, then we should stay in our lane.  But even then, we should probably consider the big picture and the associated use cases.   I really think we need a place to gather use cases.

**Comment by mvahowe** [comment]
Given recent, tragic events, there are plenty of conversations about DBL governance right now. Whatever the answer to that question, I think it's a completely separate question. Personally, I can't see any management-level team easily committing to supporting all SB flavors, past and future, and I'd expect them to ask questions about mission focus if asked to run a general-purpose registry.

**Comment by jag3773** [comment]
We discussed this in the meeting today and agree that it is an issue that needs discussed, but we noted that it is out of our Scripture Burrito scope.  Specifically, our task is to support interchange between systems.  The details of those systems and the politics of how they came to be and why they currently exist is well beyond our scope (and ability) to control.

Notes from our meeting today record:

>Aim for a system that identifies orgs by their FQDN
>  * idServer becomes a declaration that can be shorthand referred to later in the doc
>  * Scope of the prefix is the document itself
>
>Identification section will be modified to not require a whitelist of systemIDs


Scripture Burrito is analogous to EPUB; DBL (and the idea of discoverability) is analogous to Amazon's Kindle ecosystem.

We agree that discoverability is an issue and we are designing SB to support discoverability systems. Note that there is talk of an API system that could help with this (see https://github.com/bible-technology/scripture-burrito-aware-api).  In the next couple of weeks, I think the documentation and the examples will make clear that SB addresses the concerns raised to the extent that it can (and if not, we can reopen this issue after the [beta milestone](https://github.com/bible-technology/scripture-burrito/milestone/1)).

I suggest moving the discussion to https://technology.bible/ to engage a wider audience.
