### ISSUE TITLE
Document parascriptural_word_alignment.xml

### ISSUE THREAD

**Issue by jag3773** [bible-technology/scripture-burrito#41]
The docs/examples/parascriptural_word_alignment.xml example file is failing the `xmllint` test and needs fixed.  Check the [Travis build log](https://travis-ci.org/bible-technology/scripture-burrito/jobs/569981198#L229) for the exact error.

Not sure if this is for @mvahowe or @joelthe1 ...

**Comment by joelthe1** [comment]
@jag3773 , couldn't figure out what exactly is the issue. Doesn't [this](https://github.com/bible-technology/scripture-burrito/blob/master/docs/schema/metadata.rnc#L140) say that `parascripturalWordAlignment` is the correct name of the flavor?

**Comment by jag3773** [comment]
Yeah, I'm not sure either, @mvahowe may need to load it up in Oxygen and see where exactly the problem lies.

**Comment by mvahowe** [comment]
@joelthe1 @jag3773 Oxygen displayed 15 errors. Some of them were typos and/or careless copy-paste XML surgery, some were URNs, others required schema tweaks. I pushed my latest to master (forgot to do a PR, will do better next time).

The remaining part is to sort out the refs section. I can't do that because I don't know what we are trying to do there. Right now we have one lid element containing child elements and one lid element containing text. Everyone will thank you for not making both of those options valid. ie, if you are going to use child elements, ever, put everything in one or more child elements.

You could fix this around line 175 of the schema. Let me know if you need help.

Obviously I have no idea if the metadata here is actually useful, how many fields should be required, whether we could validate the syntax of any of the text fields, etc.

**Comment by joelthe1** [comment]
@mvahowe, I have Slacked you some of the changes I had in mind. Could you take a look?

**Comment by mvahowe** [comment]
@joelthe1 Thanks! I made some changes, and the metadata now validates. (@jag3773 then eventually convinced Travis that this is true :-) )

I also restructured the documentation of this flavor, in a similar style to the 5 scriptural flavors. Could you replace my text in square brackets with something more informative? This flavor has attracted a lot of interest in various places, because it's a long way from anything DBL has done before, and also because it overlaps with the remit of the Copenhagen Alliance. I think that explaining where the format came from, who has worked on it, etc, would help.

**Comment by jag3773** [comment]
Fixed in #61
