### ISSUE TITLE
Licenses and specific agreements

### ISSUE THREAD

**Issue by klassenjm** [bible-technology/scripture-burrito#67]
In 0.1, the `<licenses>` section can contain one `<license>` element. This suggests that this section (if present) is to be used for asserting what type of use(s) the burrito content is licensed for (available under).

This section does not then appear to be intended for indicating the parties of a specific agreement. For example, if party A created a burrito for party B - could the metadata when received by party B indicate that this specific burrito is intended for use by this specific receiving party organization? Is there any merit to extending it to allow this, such as:

```
<license>
    <url>https://burritos-r-us.org/licenses/3247</url>
        <!-- whether or not the agreement URI is publicly accessible -->
    <recipient><id>dbl::23</id></recipient>
</license>
```

`<recipient>` could be `<licensee>` or `<consumer>` or something else.

This would mean that if a burrito is copied from one location to another, a potential consumer could identify who the authorized consumer of that burrito is. It would allow for burritos to reflect a specific use / publishing intent (?)

_Perhaps it is sufficient to simply understand that no license metadata = no permissions_. Allowing for being specific might be of interest?

**Comment by jag3773** [comment]
> Perhaps it is sufficient to simply understand that no license metadata = no permissions.

This is what we were planning.  At least in part because:

1. If someone has the burrito then they have the content itself already (it's up to them to use it appropriately).
2. If they don't have a connection to the correct server then the id isn't meaningful, so they are back at step 1 (even if they do have a connection, it isn't actually constrained unless they are logging in somehow to validate who they are, but they already have the burrito!).
3. The URL to the license should specify the parties.  Hence `https://burritos-r-us.org/licenses/3247` should indicate the owner and the recipient.  I think any private license must explicitly identify at least those two licenses to have any validity.

In large part, we are suggesting that private licenses be handled by the various ecosystems however they currently handle them, or however they would like to handle them.  For a burrito, it should be sufficient to point to the actual license, which would be a URL or a local file.  There could be some benefits in greater specificity, but it also causes complexity to increase significantly.

**Comment by jag3773** [comment]
In reviewing issue #48, I was reminded that we do also have support for [allRightsReserved](https://docs.burrito.bible/en/latest/metadata_licenses.html#allrightsreserved).  This means that a burrito could identify itself as explicitly providing no special rights to anyone receiving it.

@klassenjm Do my comments above sufficiently address your concerns?

**Comment by klassenjm** [comment]
@jag3773 Yes, I think they do. Thanks for taking time to explain, Jesse, and for waiting on my reply.
